services:
    rbm.ed2k.listener:
        class: rbm\ed2k\event\main_listener
        arguments:
            - '@language'
            - '@template'
        tags:
            - { name: event.listener }
